name: qde_realme
description: ''
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.12.0 <4.0.0'
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  path: ^1.9.1
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4

  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.2

  # Navigation
  go_router: ^14.2.0

  # Localization
  easy_localization: ^3.0.7

  # Network
  dio: ^5.4.1
  connectivity_plus: ^6.0.5

  # Functional Programming (Error Handling)
  dartz: ^0.10.1

  # Local Storage
  shared_preferences: ^2.2.3

  # Notifications
  firebase_core: ^4.9.0

  cloud_firestore: ^6.7.1
  firebase_auth: ^6.0.2
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^8.1.0


  crypto: ^3.0.3
  camera: ^0.12.0
  google_mlkit_text_recognition: ^0.15.0
  permission_handler: ^11.3.1

  firebase_remote_config: ^6.5.5
  firebase_crashlytics: ^5.2.6


  file_picker: ^11.0.2
  excel: ^4.0.6


  # Utils
  intl: 0.20.2
  showcaseview: ^4.0.1
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/translations/uz.json
    - assets/translations/ru.json
    - assets/images/
  fonts:
    - family: gilroy
      fonts:
          - asset: assets/fonts/Gilroy-Black_0.ttf
          - asset: assets/fonts/Gilroy-BlackItalic_0.ttf
          - asset: assets/fonts/Gilroy-Bold_0.ttf
          - asset: assets/fonts/Gilroy-BoldItalic_0.ttf
          - asset: assets/fonts/Gilroy-Extrabold_0.ttf
          - asset: assets/fonts/Gilroy-ExtraboldItalic_0.ttf
          - asset: assets/fonts/Gilroy-Heavy_0.ttf
          - asset: assets/fonts/Gilroy-HeavyItalic_0.ttf
          - asset: assets/fonts/Gilroy-Light_0.ttf
          - asset: assets/fonts/Gilroy-LightItalic_0.ttf
          - asset: assets/fonts/Gilroy-Medium_0.ttf
          - asset: assets/fonts/Gilroy-MediumItalic_0.ttf
          - asset: assets/fonts/Gilroy-Regular_0.ttf
          - asset: assets/fonts/Gilroy-RegularItalic_0.ttf
          - asset: assets/fonts/Gilroy-Semibold_0.ttf
          - asset: assets/fonts/Gilroy-SemiboldItalic_0.ttf
          - asset: assets/fonts/Gilroy-Thin_0.ttf
          - asset: assets/fonts/Gilroy-ThinItalic_0.ttf
          - asset: assets/fonts/Gilroy-UltraLight_0.ttf
          - asset: assets/fonts/Gilroy-UltraLightItalic_0.ttf

flutter_native_splash:
  color: "#1C162E" # Твой HEX-цвет фона (например, #121212 для тёмного)
  image: assets/images/logo.png # Твоя иконка по центру
  fullscreen: true
  # Настройки под Android 12+ (обязательно для новых версий)
  android_12:
    color: "#1C162E"
    image: assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21